# Generated by Django 2.2.3 on 2019-11-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('faculty', models.CharField(max_length=100, verbose_name='Факультет')),
                ('course', models.CharField(max_length=100, verbose_name='Курс')),
                ('group', models.IntegerField(verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
