# Generated by Django 3.0 on 2019-12-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opros', '0002_question_textanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Вопрос',
        ),
        migrations.RemoveField(
            model_name='textanswer',
            name='Ответ',
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default='', verbose_name='Вопрос'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textanswer',
            name='answer',
            field=models.CharField(default='', max_length=255, verbose_name='Ответ'),
            preserve_default=False,
        ),
    ]
