var test = "test1";
var peremeshat_voprosi = "да";
var vopros_1 = "";
var vopros_2 = "Вопрос 2(ответ 2)";
var vopros_3 = "Вопрос 3(ответ 3)";
var vopros_4 = "";
var vopros_5 = "Вопрос 5(ответ 5)";
var vopros_6 = "Вопрос 6(ответ 6)";
var vopros_7 = "";
var vopros_8 = "Вопрос 8(ответ 8)";
var vopros_9 = "Вопрос 9(ответ 9)";
var vopros_10 = "Вопрос 10( ответ 10)";
var vopros_11 = "Вопрос 11(ответ 11)";
var vopros_12 = "Вопрос 12(ответ 12)";
var vopros_13 = "Вопрос 13(ответ 13)";
var vopros_14 = "Вопрос 14(ответ 14)";
var vopros_15 = "";
var vopros_ris_1 = "да";
var vopros_ris_2 = "нет";
var vopros_ris_3 = "нет";
var vopros_ris_4 = "да";
var vopros_ris_5 = "нет";
var vopros_ris_6 = "нет";
var vopros_ris_7 = "да";
var vopros_ris_8 = "нет";
var vopros_ris_9 = "нет";
var vopros_ris_10 = "нет";
var vopros_ris_11 = "нет";
var vopros_ris_12 = "нет";
var vopros_ris_13 = "нет";
var vopros_ris_14 = "нет";
var vopros_ris_15 = "да";
var pr_otv_zadachi_1 = "A="; 
var pr_otv_zadachi_2 = "Mg==";
var pr_otv_zadachi_3 = "Mw==";
var pr_otv_zadachi_4 = "VC";
var pr_otv_zadachi_5 = "NQ==";
var pr_otv_zadachi_6 = "Ng==";
var pr_otv_zadachi_7 = "A=";
var pr_otv_zadachi_8 = "OA==";
var pr_otv_zadachi_9 = "OQ==";
var pr_otv_zadachi_10 = "MTA=";
var pr_otv_zadachi_11 = "MTE=";
var pr_otv_zadachi_12 = "MTI=";
var pr_otv_zadachi_13 = "MTM=";
var pr_otv_zadachi_14 = "MTQ=";
var pr_otv_zadachi_15 = "VC";